// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const RegeneratePluginOptions: CLICommandOption[] = [
  {
    name: "select-plugin-manifest",
    type: "string",
    description: "Select plugin manifest file.",
    required: true,
  },
  {
    name: "select-openapi-spec-from-plugin",
    type: "string",
    description: "Select OpenAPI description document file.",
    required: true,
  },
  {
    name: "api-operation",
    type: "array",
    shortName: "o",
    description: "Select operation(s) Copilot can interact with.",
    required: true,
  },
];
export const RegeneratePluginArguments: CLICommandArgument[] = [];
