// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const SelectTeamsManifestOptions: CLICommandOption[] = [
  {
    name: "manifest-file",
    questionName: "manifest-path",
    type: "string",
    shortName: "t",
    description: "Specifies the app manifest file path.",
    required: true,
    default: "./appPackage/manifest.json",
  },
];
export const SelectTeamsManifestArguments: CLICommandArgument[] = [];
